# -*- coding: utf-8 -*-
"""credit card fraud detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YU32eon_pWB_3orhtVmeQpdIaIWLSEU-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

df=pd.read_csv("creditcard.csv")

df.shape

df.columns

df.isnull()

df['Class'].value_counts()

""""Dataset is highly imbalanced with very few fraudulent transactions(0.17%) which is require special handling"""

## EDA

## Count Plot
sns.countplot(x='Class',data=df)
plt.title("Fraud vs Non-Fraud Transaction")
plt.xticks([0,1],['Non-Fraud','Fraud'])
plt.show()

## Box Plot
plt.figure(figsize=(8,5))

sns.boxplot(x='Class',y='Amount',data=df)

plt.xticks([0,1],['Non-Fraud','Fraud'])
plt.title("Transaction Amount vs Fraud")
plt.show()

## LOG TRANSFORMATION
df['Log_Amount']=np.log1p(df['Amount'])

sns.boxplot(x='Class',y='Log_Amount',data=df)
plt.show()

## CHECKING MISSING VALUES
df['Class'].isnull().sum()

df=df.drop(['Time'],axis=1)

"""ML models performs better when features are on same scale
ESPECIALLY.(logistics regression)
          .(distance-based models)
"""

df=df.dropna(subset=['Class'])

x=df.drop('Class',axis=1)
y=df['Class']

## Train-Test Split
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42,stratify=y)


## standard scaler
sc = StandardScaler()

x_train = x_train.copy()
x_test = x_test.copy()

x_train.loc[:,'Amount'] = sc.fit_transform(x_train[['Amount']]).ravel()
x_test.loc[:,'Amount'] = sc.transform(x_test[['Amount']]).ravel()

""""The 'Amount' feature was standarddized using StandardScaler,while PCA-transformed
features were left unchanged.Stratified train-test split was used to preserve class distribution"

"""

df

""".Reduces non-fraud cases
.makes dataset balanced
*downside(lose a lot of data)
"""

## Method 1:Random Undersampling (Simple)
from imblearn.under_sampling import RandomUnderSampler

rus=RandomUnderSampler(random_state=42)
x_res,y_res=rus.fit_resample(x_train,y_train)

"""(SMOTE) creates synthetic fraud samples, it increases fraud cases and keeps all original data

more realistic and better model performance
"""

## using SMOTE (Synthetic Minority Over-Sampling Technique)
from imblearn.over_sampling import SMOTE

smote=SMOTE(random_state=42)
x_res,y_res=smote.fit_resample(x_train,y_train)

pd.Series(y_res).value_counts()

x_train.shape

x_res.shape

#"Due to extreme class imbalance,Random Undersampling and smote were applied.
#SMOTE generated synthetic minority samples,improving model performance compared to under sampling"
## 1.Logistic Regression
from sklearn.linear_model import LogisticRegression

lr_model=LogisticRegression(max_iter=1000)
lr_model.fit(x_res,y_res)

## predictions
y_pred_lr=lr_model.predict(x_test)

## 2.Random Forest
from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier(n_estimators=100,random_state=42,n_jobs=-1)
rf_model.fit(x_res,y_res)

## Predictions
y_pred_rf=rf_model.predict(x_test)

"""EVALUATION START

"""

## Using Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix

## Logistic Regression Evaluation
print("Logistic Regression:\n")
print(confusion_matrix(y_test,y_pred_lr))
print(classification_report(y_test,y_pred_lr))

## Random Forest Evaluation
print("RandomForest:\n")
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

"""Now we are going to tune our model"""

## Grid Search CV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid={
    'n_estimators':[50,100],
    'max_depth':[5,10,],
    'min_samples_split':[2,5]
}

rf=RandomForestClassifier(random_state=42)

random_search=RandomizedSearchCV(
    rf,
    param_grid,
    n_iter=8,
    cv=3,
    scoring='f1',## important for the imbalance
    n_jobs=-1,
    verbose=1,
    random_state=42
)

random_search.fit(x_res,y_res)

print("Best Parameters:",random_search.best_params_)

## train best model
best_rf=random_search.best_estimator_

y_pred_best=best_rf.predict(x_test)

## EVALUATION
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred_best))

## XGBOOST
from xgboost import XGBClassifier

xgb_model=XGBClassifier(
    n_estimators=100,
    max_depth=5,
    learning_rate=0.1,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(x_res,y_res)

y_pred_xgb=xgb_model.predict(x_test)

## EVALUATION
from sklearn.metrics import classification_report

print("XGBoost:\n")
print(classification_report(y_test,y_pred_xgb))

from sklearn.metrics import roc_curve, roc_auc_score

## Get Probabilities
y_prob=random_search.best_estimator_.predict_proba(x_test)[:,1]

fpr,tpr,_=roc_curve(y_test,y_prob)
auc_score=roc_auc_score(y_test,y_prob)

plt.figure()
plt.plot(fpr,tpr,label=f"AUC={auc_score:.3f}")
plt.plot([0,1],[0,1],linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve-Random Forest")
plt.legend()
plt.show()

print("AUC Score:",auc_score)

## Model Comparison Table
from sklearn.metrics import f1_score, roc_auc_score

models={
    "Logistic Regression":lr_model,
    "Random Forest":best_rf,
    "XGBoost":xgb_model
    }

for name,model in models.items():
  y_pred=model.predict(x_test)
  y_prob=model.predict_proba(x_test)[:,1]

  print(f"{name}:")
  print("f1 Score:",f1_score(y_test,y_pred))
  print("AUC:",roc_auc_score(y_test,y_prob))
  print("-"*30)

## Feature Importance
importances=best_rf.feature_importances_
feat_imp=pd.Series(importances,index=x_train.columns).sort_values(ascending=False)

print(feat_imp.head(10))

## feature plot
feat_imp.head(10).plot(kind='bar')
plt.title("Top Features")
plt.show()

## Threshold Tuning
from sklearn.metrics import f1_score

#using the best random forest probabilities
y_prob=best_rf.predict_proba(x_test)[:,1]
thresholds=np.linspace(0.1,0.9,50)
f1_scores=[]

for t in thresholds:
  y_pred_t=(y_prob >=t).astype(int)
  f1_scores.append(f1_score(y_test,y_pred_t))

best_threshold = thresholds[np.argmax(f1_scores)]

print("Best Threshold:",best_threshold)

## threshold comaparision
from sklearn.metrics import f1_score, precision_score, recall_score
y_prob=best_rf.predict_proba(x_test)[:,1]
for t in [0.6,0.7,0.9]:
  y_pred_t=(y_prob >= t).astype(int)

  print(f"Threshold:{t}")
  print("F1:",f1_score(y_test,y_pred_t))
  print("Precision:",precision_score(y_test,y_pred_t))
  print("Recall:",recall_score(y_test,y_pred_t))
  print("-"*30)

## Precision recall curve
from sklearn.metrics import precision_recall_curve
precision,recall,_=precision_recall_curve(y_test,y_prob)

plt.plot(recall,precision)
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")
plt.show()

